#!/bin/sh

DMENU_WHITELIST="
google-chrome
personal-google-chrome.sh
work-google-chrome.sh
firefox
code
spotify
KeeWeb
nautilus
slack
dbeaver
intellij-idea-community
"

echo $DMENU_WHITELIST | sed 's*\s*\n*g' | dmenu -i | ${SHELL:-"/bin/sh"} &
