#!/bin/sh

DMENU_WHITELIST="
google-chrome
sergej-chrome.sh
zlab-chrome.sh
firefox
pycharm-community
code
spotify
KeeWeb
nautilus
slack
dbeaver
"

echo $DMENU_WHITELIST | sed 's*\s*\n*g' | dmenu -i | ${SHELL:-"/bin/sh"} &
